USE ROLE ACCOUNTADMIN; 
USE DATABASE ZOMATO; 
USE SCHEMA RAW; 

-- Creating File Format 
CREATE OR REPLACE FILE FORMAT ZOMATO.RAW.CSV_FMT
    TYPE = "CSV"
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', '\\N', 'NULL')
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE; 

-- Creating Stage 
CREATE OR REPLACE STAGE ZOMATO.RAW.ZOMATO_RAW_STAGE
    STORAGE_INTEGRATION = ZOMATO_S3_INT
    URL = 'S3://project-zomato-data-060662064877-us-east-1-an/'
    FILE_FORMAT = ZOMATO.RAW.CSV_FMT;

LIST @ZOMATO.RAW.ZOMATO_RAW_STAGE; 

    

